name: Auto GitHub Contributions

on:
  schedule:
    - cron: '0 9 * * *'
    - cron: '40 9 * * *'
    - cron: '20 10 * * *'
    - cron: '0 11 * * *'
    - cron: '40 11 * * *'
    - cron: '20 12 * * *'
    - cron: '0 13 * * *'
    - cron: '40 13 * * *'
    - cron: '20 14 * * *'
    - cron: '0 15 * * *'
    - cron: '40 15 * * *'
    - cron: '20 16 * * *'
    - cron: '0 17 * * *'
    - cron: '40 17 * * *'
    - cron: '20 18 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # ensures history is fetched so we can commit
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Configure Git for Green Squares
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          
      - name: Run Auto Push Script
        run: python auto_push.py
